{{- range $name, $svc := .Values.services }}
{{- if $svc.storage }}
{{- $labels := dict "root" $ "name" $name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-pvc
  labels:
    {{- include "helmgen.labels" $labels | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $svc.storageSize | default "1Gi" }}
---
{{- end }}
{{- end }}
