{{- range $name, $svc := .Values.services }}
{{- if and (eq $.Values.secretProvider "internal") ($svc.secrets) }}
{{- $labels := dict "root" $ "name" $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-secret
  labels:
    {{- include "helmgen.labels" $labels | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := $svc.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
