{{- if and (eq $.Values.secretProvider "externalsecret") (not $.Values.reuseStore) }}
apiVersion: external-secrets.io/v1beta1
kind: {{ ternary "ClusterSecretStore" "SecretStore" (eq $.Values.storeScope "cluster") }}
metadata:
  name: {{ $.Release.Name }}-secretstore
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}-secretstore
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helmgen.io/generated: "true"
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret/"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-auth"
          key: "token"
{{- end }}
